import { ToolRegistry } from "./registry.js";

// planning / bibles
import { readProjectTool } from "./planning/readProject.js";
import { updateProjectTool } from "./planning/updateProject.js";
import { analyzeRequestTool } from "./planning/analyzeRequest.js";
import { createPromptPlanTool } from "./planning/createPromptPlan.js";
import { updateStyleBibleTool } from "./planning/updateStyleBible.js";
import { updateCharacterBibleTool } from "./planning/updateCharacterBible.js";
import { updateEnvironmentBibleTool } from "./planning/updateEnvironmentBible.js";

// story & scene prompts
import { createStoryStructureTool } from "./script/createStoryStructure.js";
import { generateScenePromptsTool } from "./scenes/generateScenePrompts.js";
import { regenerateScenePromptTool } from "./scenes/regenerateScenePrompt.js";
import { updateSceneTool } from "./scenes/updateScene.js";
import { addScenesTool } from "./scenes/addScenes.js";
import { removeSceneTool } from "./scenes/removeScene.js";
import { moveSceneTool } from "./scenes/moveScene.js";

// media / upload / timeline
import { listMediaTool } from "./media/listMedia.js";
import { inspectMediaTool } from "./media/inspectMedia.js";
import { matchMediaToSceneTool } from "./media/matchMediaToScene.js";
import { assignMediaToSceneTool } from "./media/assignMediaToScene.js";
import { removeMediaTool } from "./media/removeMedia.js";
import { replaceMediaTool } from "./media/replaceMedia.js";
import { reorderMediaTool } from "./media/reorderMedia.js";
import { setImageDurationTool } from "./media/setImageDuration.js";
import { buildTimelineTool } from "./media/buildTimeline.js";

// assembly & validation
import { renderTimelineTool } from "./media/renderTimeline.js";
import { setAudioTrackTool } from "./audio/setAudioTrack.js";
import { addNarrationTool } from "./audio/addNarration.js";
import { addMusicTool } from "./audio/addMusic.js";
import { generateSubtitlesTool } from "./audio/generateSubtitles.js";
import { addSubtitlesTool } from "./audio/addSubtitles.js";
import { createThumbnailTool } from "./media/createThumbnail.js";
import { validateVideoTool } from "./validation/validateVideo.js";
import { generateBackgroundPromptTool } from "./branding/generateBackgroundPrompt.js";
import { generateYoutubeMetadataTool } from "./branding/generateYoutubeMetadata.js";

/**
 * Builds the tool registry available to the agent: prompt generation
 * (analyze -> plan -> story structure -> scene prompts -> continuity edits)
 * and upload/timeline/assembly (media never generated by this app - always
 * uploaded by the user, then normalized and assembled locally with
 * FFmpeg). Grows without ever touching AgentLoop - new tools just get
 * registered here.
 */
export function buildToolRegistry(): ToolRegistry {
  const registry = new ToolRegistry();

  registry.register(readProjectTool);
  registry.register(updateProjectTool);
  registry.register(analyzeRequestTool);

  registry.register(createPromptPlanTool);
  registry.register(updateStyleBibleTool);
  registry.register(updateCharacterBibleTool);
  registry.register(updateEnvironmentBibleTool);

  registry.register(createStoryStructureTool);
  registry.register(generateScenePromptsTool);
  registry.register(regenerateScenePromptTool);
  registry.register(updateSceneTool);
  registry.register(addScenesTool);
  registry.register(removeSceneTool);
  registry.register(moveSceneTool);
  registry.register(generateBackgroundPromptTool);
  registry.register(generateYoutubeMetadataTool);

  registry.register(listMediaTool);
  registry.register(inspectMediaTool);
  registry.register(matchMediaToSceneTool);
  registry.register(assignMediaToSceneTool);
  registry.register(removeMediaTool);
  registry.register(replaceMediaTool);
  registry.register(reorderMediaTool);
  registry.register(setImageDurationTool);
  registry.register(buildTimelineTool);

  registry.register(renderTimelineTool);
  registry.register(setAudioTrackTool);
  registry.register(addNarrationTool);
  registry.register(addMusicTool);
  registry.register(generateSubtitlesTool);
  registry.register(addSubtitlesTool);
  registry.register(createThumbnailTool);
  registry.register(validateVideoTool);

  return registry;
}

/**
 * The single shared registry instance used by both the agent loop (via
 * VideoAgent's default constructor param) and any route that needs to run
 * a tool directly (e.g. a UI-triggered "regenerate this scene prompt"
 * button) - so a manual action goes through the exact same versioning code
 * path as an LLM-triggered one.
 */
export const toolRegistry = buildToolRegistry();
